### ISSUE TITLE
Improve Coverage for API layer

### ISSUE THREAD

**Issue by jjirinec** [Palmyra-Racing-Association/trackboss#242]
Add additional tests to complete code coverage for the following
- [ ] GET job/list for filters
- [ ] GET member/list user input error
- [ ] PATCH member/:memberId header fail
- [ ] PATCH member/:memberId 401 auth fail
- [ ] Member DB getValidActors DB error
- [ ] Add cases for `membershipId` filters to the API tests
- [ ] Add cases for `membershipId` filters to the DB tests
- [ ] Add cases for membershipApplications
- [ ] Add cases for gateCode
- [ ] Add cases for other stuff I'm forgetting right now.

**Comment by adelimon** [comment]
See #396 , this can close.
